apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
  namespace: order-service
  labels:
    app.kubernetes.io/name: order-microservice
    app.kubernetes.io/component: config
data:
  PORT: "3000"
  NODE_ENV: "production"
  JWT_EXPIRES_IN: "1h"
  SERVICE_NAME: "order-microservice"
  SERVICE_VERSION: "1.0.0"

  # ── Observability ──────────────────────────────────────────────────────────
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://alloy.alloy.svc.cluster.local:4318"
  LOKI_HOST: "http://loki.loki.svc.cluster.local:3100"
  CORS_ALLOWED_ORIGINS: "https://dash.sxdentrypoint.my.id,https://app.sxdentrypoint.my.id"
