apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Target namespace for all resources in this kustomization
namespace: order-service

resources:
  - namespace.yaml
  - sa.yaml
  - registry-secret.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - pdb.yaml

# Labels applied to all resources and selectors
commonLabels:
  app.kubernetes.io/name: order-microservice
  app.kubernetes.io/managed-by: kustomize
