apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: order-service-pdb
  namespace: order-service
  labels:
    app.kubernetes.io/name: order-microservice
    app.kubernetes.io/component: pdb
spec:
  minAvailable: 1 # Setidaknya 1 pod harus tetap jalan saat terjadi gangguan (disruption)
  selector:
    matchLabels:
      app: order-service
