apiVersion: v1
kind: Secret
metadata:
  name: order-service-secret
  namespace: order-service
  labels:
    app.kubernetes.io/name: order-microservice
    app.kubernetes.io/component: secret
type: Opaque
data:
  # DATABASE_URL disesuaikan ke order_db
  # echo -n "postgresql://postgres:yourpassword@postgres-svc.postgres.svc.cluster.local:5432/order_db" | base64
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnlvdXJwYXNzd29yZEBwb3N0Z3Jlcy1zdmMucG9zdGdyZXMuc3ZjLmNsdXN0ZXIubG9jYWw6NTQzMi9vcmRlcl9kYg==

  # JWT_SECRET (Sebaiknya generate ulang untuk service yang berbeda)
  # echo -n "$(openssl rand -hex 64)" | base64
  JWT_SECRET: YzcyNjczZTU3MmQwMmJhMWMwMmQzY2ZiZjIwZjY1MjMzMGJkZGJiZTg3NDI3OTE3NGIzNWRhMjRhZDk1N2RhY2NkZGNlZWNiMzE4M2MyMjU1NDUxMTA0MjQ4MjBhMThkNGI3YWMzN2Q5MzBlNGY3NTFkZGUxNzM4YTNjZWU5NDM=

  # ADMIN_USERNAME: admin
  ADMIN_USERNAME: YWRtaW4=

  # ADMIN_PASSWORD: YourStrongAdminPassword!
  ADMIN_PASSWORD: WW91clN0cm9uZ0FkbWluUGFzc3dvcmQh
