apiVersion: v1
kind: Secret
metadata:
  name: order-service-secret
  namespace: order-service
  labels:
    app.kubernetes.io/name: order-microservice
    app.kubernetes.io/component: secret
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOjVoQjI0cmk2TXE4SEBvcmRlci1wb3N0Z3Jlcy1oZWFkbGVzcy5vcmRlci1wb3N0Z3Jlcy5zdmMuY2x1c3Rlci5sb2NhbDo1NDMyL29yZGVyX2Ri
  JWT_SECRET: Y2VmOTA2YWEyZThhZDA4ZDliN2U1NGQwZmU3NWU5OTY3MDc5MjU1ZDAzNzI0MWIwMTJjODVjMTYyZDBlMTJmZjljYWQwNWQwZDc5OGY0ZjQ2MzdlNjU1NWE5NDYwNGYxMzQyYWQwNjNhMzcwODg3ZDIwYzhmMzc0ZWMyMGJiNGI=
  ADMIN_USERNAME: YWRtaW4=
  ADMIN_PASSWORD: QWRtaW5AMTIzNCE=
  INTERNAL_SERVICE_SECRET: ZDk5ZDA2YWRkZDNmMGNiNTJhMTEzOGExNzMyN2IzZGQxY2M3M2M3YWY2MDRkNjBlZWIxOTM4MzM2MzliY2Ri
  BOOK_SERVICE_URL: aHR0cDovL2Jvb2stc2VydmljZS5ib29rLXNlcnZpY2Uuc3ZjLmNsdXN0ZXIubG9jYWw6MzAwMA==
  BLOCKCHAIN_SERVICE_URL: aHR0cDovL2Jsb2NrY2hhaW4tc2VydmljZS5ibG9ja2NoYWluLXNlcnZpY2Uuc3ZjLmNsdXN0ZXIubG9jYWw6MzAwMA==
