apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: order-service
  labels:
    app.kubernetes.io/name: order-microservice
    app.kubernetes.io/component: server
spec:
  type: ClusterIP
  selector:
    app: order-service # Harus cocok dengan label 'app' di Deployment order
  ports:
    - name: http
      port: 80 # Port yang diakses oleh service lain di dalam cluster
      targetPort: http # Merujuk ke containerPort (misal: 3000) di Deployment
      protocol: TCP
